INSERT INTO items (name,description) VALUES ('item 1','description for item 1'),
	                                        ('item 2','description for item 2'),
	                                        ('item 3','description for item 3'),
	                                        ('item 4','description for item 4'),
	                                        ('item 5','description for item 5'),
	                                        ('item 6','description for item 6'),
	                                        ('item 7','description for item 7'),
	                                        ('item 8','description for item 8'),
	                                        ('item 9','description for item 9'),
	                                        ('item 10','description for item 10'),
	                                        ('item 11','description for item 11'),
	                                        ('item 12','description for item 12'),
	                                        ('item 13','description for item 13'),
	                                        ('item 14','description for item 14'),
	                                        ('item 15','description for item 15'),
	                                        ('item 16','description for item 16'),
	                                        ('item 17','description for item 17'),
	                                        ('item 18','description for item 18'),
	                                        ('item 19','description for item 19'),
	                                        ('item 20','description for item 20');


